
Loading components for TIF035

Traceback (most recent call last):
  File "./bulkAl.py", line 18, in <module>
    bulk= FaceCenteredCubic(directions=[[1,-1,0], [1,1,-2], [1,1,1]],
NameError: name 'FaceCenteredCubic' is not defined
GPAW CLEANUP (node 7): <type 'exceptions.NameError'> occurred.  Calling MPI_Abort!
Traceback (most recent call last):
  File "./bulkAl.py", line 18, in <module>
    bulk= FaceCenteredCubic(directions=[[1,-1,0], [1,1,-2], [1,1,1]],
NameError: name 'FaceCenteredCubic' is not defined
GPAW CLEANUP (node 6): <type 'exceptions.NameError'> occurred.  Calling MPI_Abort!
Traceback (most recent call last):
  File "./bulkAl.py", line 18, in <module>
    bulk= FaceCenteredCubic(directions=[[1,-1,0], [1,1,-2], [1,1,1]],
NameError: name 'FaceCenteredCubic' is not defined
GPAW CLEANUP (node 5): <type 'exceptions.NameError'> occurred.  Calling MPI_Abort!
Traceback (most recent call last):
  File "./bulkAl.py", line 18, in <module>
    bulk= FaceCenteredCubic(directions=[[1,-1,0], [1,1,-2], [1,1,1]],
NameError: name 'FaceCenteredCubic' is not defined
GPAW CLEANUP (node 3): <type 'exceptions.NameError'> occurred.  Calling MPI_Abort!
Traceback (most recent call last):
  File "./bulkAl.py", line 18, in <module>
    bulk= FaceCenteredCubic(directions=[[1,-1,0], [1,1,-2], [1,1,1]],
NameError: name 'FaceCenteredCubic' is not defined
GPAW CLEANUP (node 1): <type 'exceptions.NameError'> occurred.  Calling MPI_Abort!
Traceback (most recent call last):
  File "./bulkAl.py", line 18, in <module>
    bulk= FaceCenteredCubic(directions=[[1,-1,0], [1,1,-2], [1,1,1]],
NameError: name 'FaceCenteredCubic' is not defined
GPAW CLEANUP (node 4): <type 'exceptions.NameError'> occurred.  Calling MPI_Abort!
Traceback (most recent call last):
  File "./bulkAl.py", line 18, in <module>
    bulk= FaceCenteredCubic(directions=[[1,-1,0], [1,1,-2], [1,1,1]],
NameError: name 'FaceCenteredCubic' is not defined
GPAW CLEANUP (node 0): <type 'exceptions.NameError'> occurred.  Calling MPI_Abort!
Traceback (most recent call last):
  File "./bulkAl.py", line 18, in <module>
    bulk= FaceCenteredCubic(directions=[[1,-1,0], [1,1,-2], [1,1,1]],
NameError: name 'FaceCenteredCubic' is not defined
GPAW CLEANUP (node 2): <type 'exceptions.NameError'> occurred.  Calling MPI_Abort!
--------------------------------------------------------------------------
MPI_ABORT was invoked on rank 7 in communicator MPI_COMM_WORLD 
with errorcode 42.

NOTE: invoking MPI_ABORT causes Open MPI to kill all MPI processes.
You may or may not see output from other processes, depending on
exactly when Open MPI kills them.
--------------------------------------------------------------------------
--------------------------------------------------------------------------
mpirun has exited due to process rank 7 with PID 13168 on
node beda63-2.nfs.private exiting without calling "finalize". This may
have caused other processes in the application to be
terminated by signals sent by mpirun (as reported here).
--------------------------------------------------------------------------
